apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      name: alertmanager
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:latest
        env:
          - name: SLACK_HOOK_URL
            valueFrom:
              secretKeyRef:
                name: slack-hook-url
                key: slack-hook-url
        command: ['/bin/sh', '/etc/alertmanager/configure_secret.sh']
        ports:
        - name: alertmanager
          containerPort: 9093
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager
      - name: tmp-volume
        emptyDir: {}
      nodeSelector:
        kubernetes.io/os: linux

