name: Deploy Infrastructure and Configure AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.4

    - name: Cache Terraform plugins
      uses: actions/cache@v3
      with:
        path: ~/.terraform.d/plugin-cache
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
        restore-keys: |
          ${{ runner.os }}-terraform-

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Install jq
      run: |
        sudo apt-get install -y jq

    - name: Extract Azure Credentials
      id: azure-creds
      run: |
        echo "::set-output name=client_id::$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .clientId)"
        echo "::set-output name=client_secret::$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .clientSecret)"
        echo "::set-output name=tenant_id::$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .tenantId)"
        echo "::set-output name=subscription_id::$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .subscriptionId)"

    - name: Azure CLI Login
      env:
        AZURE_CLIENT_ID: ${{ steps.azure-creds.outputs.client_id }}
        AZURE_CLIENT_SECRET: ${{ steps.azure-creds.outputs.client_secret }}
        AZURE_TENANT_ID: ${{ steps.azure-creds.outputs.tenant_id }}
      run: |
        az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.30.3'

    - name: Create Azure Resource Group and Storage Account for Terraform Backend
      env:
        AZURE_CLIENT_ID: ${{ steps.azure-creds.outputs.client_id }}
        AZURE_CLIENT_SECRET: ${{ steps.azure-creds.outputs.client_secret }}
        AZURE_TENANT_ID: ${{ steps.azure-creds.outputs.tenant_id }}
      run: |
        az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
        sudo az group create --name backend-rg --location southafricanorth
        sudo az storage account create --resource-group backend-rg --name tfbackend101 --sku Standard_LRS --encryption-services blob
        sudo az storage container create --name tfstate --account-name tfbackend101

    - name: Run inline bash script
      run: |
        chmod +x ./authorized_ips.sh
      working-directory: ./capstone_terraform

    - name: Run inline bash script
      run: |
        ./authorized_ips.sh
      working-directory: ./capstone_terraform

    - name: Terraform Init
      run: terraform init
      working-directory: ./capstone_terraform

    - name: Terraform Apply
      run: terraform apply --auto-approve
      working-directory: ./capstone_terraform

    - name: Commit .terraform.lock.hcl
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .terraform.lock.hcl
        git commit -m "Update .terraform.lock.hcl"
        git push
      working-directory: ./capstone_terraform

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y software-properties-common
        sudo add-apt-repository --yes --update ppa:ansible/ansible
        sudo apt install -y ansible

    - name: Run Ansible Playbook
      env:
        ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      run: |
        echo "$ANSIBLE_VAULT_PASSWORD" > vault_password.txt
        ansible-playbook clusterconfig_playbook.yaml --vault-password-file vault_password.txt

    - name: Clean up
      if: always()
      run: rm -f vault_password.txt